In [1]:
import numpy as np

### Create a new array of 3*2 float numbers, filled with ones.

In [2]:
np.full((3,2),1,dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Let `x = np.arange(4, dtype=np.int64)`. Create an array of ones with the same shape and type as X.
### Hint: uses `np.ones_like()`

In [16]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

### Create a new array of 3*2 float numbers, filled with zeros.

In [14]:
np.full((3,2),0,dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.
### Hint: use `np.zeros_like()`

In [15]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

### Create a new array of shape 2*5 , filled with 6.

In [19]:
np.full((2,5),6,dtype=int)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Create an array of [1, 2, 3].

In [22]:
x=np.arange(4)
x[1:]

array([1, 2, 3])

### Let x = [1, 2]. Convert it into an array.
### Hint: use `np.asarray()`

In [23]:
x = [1, 2]
np.asarray(x)

array([1, 2])

### Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.
### Hint: use `np.asmatrix()`

In [24]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

### Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.
### Hint: use `x.item()` or `x[0]`

In [26]:
x = np.array([30])
x[0]

30

### Create an array of 2, 4, 6, 8, ..., 100.

In [29]:
np.linspace(2,100,50,dtype=int)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.
### Hint: use `np.linspace()`

In [30]:
np.linspace(2,10,50)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

### Create a 1-D array of 50 element spaced evenly between 3. and 10., exclude 10.
### Hint: add parameter `endpoint=False`

In [31]:
np.linspace(2,10,50,endpoint=False)

array([2.  , 2.16, 2.32, 2.48, 2.64, 2.8 , 2.96, 3.12, 3.28, 3.44, 3.6 ,
       3.76, 3.92, 4.08, 4.24, 4.4 , 4.56, 4.72, 4.88, 5.04, 5.2 , 5.36,
       5.52, 5.68, 5.84, 6.  , 6.16, 6.32, 6.48, 6.64, 6.8 , 6.96, 7.12,
       7.28, 7.44, 7.6 , 7.76, 7.92, 8.08, 8.24, 8.4 , 8.56, 8.72, 8.88,
       9.04, 9.2 , 9.36, 9.52, 9.68, 9.84])

Lex x be an array  
`[[ 1 2 3],
[ 4 5 6]]`.

and y be an array  
`[[ 7 8 9],
[10 11 12]]`.

Concatenate x and y so that a new array looks like  
`[[1, 2, 3, 7, 8, 9],
[4, 5, 6, 10, 11, 12]]`.

In [33]:
x=[[ 1, 2, 3], [ 4, 5, 6]]
y=[[ 7, 8, 9], [10, 11, 12]]
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Concatenate x and y so that a new array looks like  
`[[ 1  2  3],
 [ 4  5  6],
 [ 7  8  9],
 [10 11 12]]`.

In [36]:
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [39]:
x=np.arange(9)
np.split(x,(4,6))

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]